import {
    createUserAccount,
    getUserById,
    getUserDocById,
    getPublicUserById,
    updateProfilePicture,
    getCloseContactsQuery,
    getCloseContacts,
    followUser,
    unfollowUser,
    addNotificationId,
    removeNotificationId,
} from "./accounts";

import {
    startTrip,
    setTripActive,
    endTrip,
    updateLocation,
    createTrip,
    createHoliday,
    updateTrip,
    updateHoliday,
    getHolidayTrips,
    getUserHoliday,
    deleteTrip,
    deleteHoliday,
    getCreatedUserTrips,
    getEndedUserTrips,
} from "./trips";

import {
    getUserNotifications,
    createCloseContactNotification,
    getSentNotifications,
    createLocationNotification,
    createLikeNotification,
    acceptNotification,
} from "./notifications";

import {
    createPost,
    getPosts,
    getPostsFromUsers,
    likePost,
    removeLikePost,
    deletePost,
} from "./posts";

export {
    createUserAccount,
    getUserById,
    getUserDocById,
    getPublicUserById,
    updateProfilePicture,
    startTrip,
    setTripActive,
    endTrip,
    updateLocation,
    createTrip,
    createHoliday,
    updateTrip,
    updateHoliday,
    getHolidayTrips,
    getUserHoliday,
    deleteTrip,
    deleteHoliday,
    getCreatedUserTrips,
    getEndedUserTrips,
    getCloseContactsQuery,
    getCloseContacts,
    followUser,
    unfollowUser,
    addNotificationId,
    removeNotificationId,
    getUserNotifications,
    createCloseContactNotification,
    getSentNotifications,
    createLocationNotification,
    createLikeNotification,
    acceptNotification,
    createPost,
    getPosts,
    getPostsFromUsers,
    likePost,
    removeLikePost,
    deletePost,
};
